---

- hosts: k3s_cluster
  gather_facts: yes
  roles:
    - role: prereq
    - role: download
#    - role: raspbian


- hosts: master
  roles:
    - role: k3s/master

- hosts: node
  roles:
    - role: k3s/node


- hosts: master
  roles:
    - role: cape
